version: '3.1'

services:

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
      - ./wordpress:/var/www
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - net

  php:    
    build: ./build/php
    container_name: php
    restart: unless-stopped
    user: "1500:1000"
    depends_on:
      - db
      - certbot
    volumes:
      - ./wordpress:/var/www
      - ./nginx/php/php-fpm.conf:/etc/php${PHP_VERSION}/php-fpm.conf
      - ./nginx/php/php.ini:/etc/php${PHP_VERSION}/conf.d/50-setting.ini
    networks:
      - net

  db:
    container_name: "mysql"
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - wp-data:/var/lib/mysql
      - ./db/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "3306:3306"
    networks:
      - net

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - net


networks:
  net:
volumes:
  wp-data:
